import { BackgroundSuggestion } from "./types";

export const BACKGROUND_PRESETS: BackgroundSuggestion[] = [
  // 1. SOLID CLASSICS (White, Light Gray, Black)
  {
    id: "bg-solid-white",
    name: "Pure Marketplace White",
    category: "solid",
    type: "color",
    value: "#FFFFFF",
    previewThumbnail: "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='80' height='80'><rect width='80' height='80' fill='%23FFFFFF'/><rect width='78' height='78' x='1' y='1' fill='none' stroke='%23E2E8F0' stroke-width='2'/></svg>",
    description: "Standard Amazon/Shopify clean white backdrop with natural contact shadow",
    badge: "Marketplace Standard",
    lighting: {
      shadowIntensity: 0.35,
      shadowBlur: 14,
      shadowOffsetX: 0,
      shadowOffsetY: 12,
      groundReflection: false,
    },
  },
  {
    id: "bg-solid-light-gray",
    name: "Studio Light Gray",
    category: "solid",
    type: "color",
    value: "#F3F4F6",
    previewThumbnail: "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='80' height='80'><rect width='80' height='80' fill='%23F3F4F6'/></svg>",
    description: "Neutral studio gray (10% tint) that highlights white & bright colored products",
    badge: "High Contrast",
    lighting: {
      shadowIntensity: 0.4,
      shadowBlur: 16,
      shadowOffsetX: 0,
      shadowOffsetY: 14,
      groundReflection: false,
    },
  },
  {
    id: "bg-solid-slate-subtle",
    name: "Cool Whisper Gray",
    category: "solid",
    type: "color",
    value: "#E2E8F0",
    previewThumbnail: "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='80' height='80'><rect width='80' height='80' fill='%23E2E8F0'/></svg>",
    description: "Slightly deeper slate for luxury tech and metallic gear",
    lighting: {
      shadowIntensity: 0.45,
      shadowBlur: 18,
      shadowOffsetX: 0,
      shadowOffsetY: 16,
      groundReflection: false,
    },
  },
  {
    id: "bg-solid-black",
    name: "Luxury Midnight Black",
    category: "solid",
    type: "color",
    value: "#0B0F17",
    previewThumbnail: "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='80' height='80'><rect width='80' height='80' fill='%230B0F17'/></svg>",
    description: "Deep premium dark canvas for watches, perfumes, jewelry and flagships",
    badge: "Luxury Edition",
    lighting: {
      shadowIntensity: 0.6,
      shadowBlur: 24,
      shadowOffsetX: 0,
      shadowOffsetY: 18,
      groundReflection: true,
      ambientLightColor: "#1E293B",
      ambientLightIntensity: 0.3,
    },
  },

  // 2. SOFT GRADIENTS
  {
    id: "bg-grad-warm-sunset",
    name: "Warm Sunset Blush",
    category: "gradient",
    type: "gradient",
    value: "linear-gradient(135deg, #FFF7ED 0%, #FFEDD5 40%, #FFE4E6 100%)",
    previewThumbnail: "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='80' height='80'><defs><linearGradient id='g' x1='0' y1='0' x2='1' y2='1'><stop offset='0%25' stop-color='%23FFF7ED'/><stop offset='40%25' stop-color='%23FFEDD5'/><stop offset='100%25' stop-color='%23FFE4E6'/></linearGradient></defs><rect width='80' height='80' fill='url(%23g)'/></svg>",
    description: "Gentle peach-to-rose warm tones ideal for cosmetics and fashion",
    lighting: {
      shadowIntensity: 0.3,
      shadowBlur: 15,
      shadowOffsetX: 0,
      shadowOffsetY: 12,
      groundReflection: false,
    },
  },
  {
    id: "bg-grad-cool-slate",
    name: "Nordic Mist Gradient",
    category: "gradient",
    type: "gradient",
    value: "linear-gradient(135deg, #F8FAFC 0%, #E2E8F0 50%, #CBD5E1 100%)",
    previewThumbnail: "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='80' height='80'><defs><linearGradient id='g' x1='0' y1='0' x2='1' y2='1'><stop offset='0%25' stop-color='%23F8FAFC'/><stop offset='50%25' stop-color='%23E2E8F0'/><stop offset='100%25' stop-color='%23CBD5E1'/></linearGradient></defs><rect width='80' height='80' fill='url(%23g)'/></svg>",
    description: "Modern Scandinavian clean slate gradient for electronics and appliances",
    lighting: {
      shadowIntensity: 0.35,
      shadowBlur: 18,
      shadowOffsetX: 0,
      shadowOffsetY: 14,
      groundReflection: false,
    },
  },
  {
    id: "bg-grad-pastel-violet",
    name: "Pastel Lavender Glow",
    category: "gradient",
    type: "gradient",
    value: "linear-gradient(135deg, #FAF5FF 0%, #EDE9FE 50%, #DDD6FE 100%)",
    previewThumbnail: "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='80' height='80'><defs><linearGradient id='g' x1='0' y1='0' x2='1' y2='1'><stop offset='0%25' stop-color='%23FAF5FF'/><stop offset='50%25' stop-color='%23EDE9FE'/><stop offset='100%25' stop-color='%23DDD6FE'/></linearGradient></defs><rect width='80' height='80' fill='url(%23g)'/></svg>",
    description: "Soft violet aura popular for skincare, perfumes and lifestyle apparel",
    lighting: {
      shadowIntensity: 0.35,
      shadowBlur: 16,
      shadowOffsetX: 0,
      shadowOffsetY: 12,
      groundReflection: false,
    },
  },
  {
    id: "bg-grad-mint-fresh",
    name: "Mint Freshness",
    category: "gradient",
    type: "gradient",
    value: "linear-gradient(135deg, #F0FDF4 0%, #DCFCE7 50%, #BBF7D0 100%)",
    previewThumbnail: "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='80' height='80'><defs><linearGradient id='g' x1='0' y1='0' x2='1' y2='1'><stop offset='0%25' stop-color='%23F0FDF4'/><stop offset='50%25' stop-color='%23DCFCE7'/><stop offset='100%25' stop-color='%23BBF7D0'/></linearGradient></defs><rect width='80' height='80' fill='url(%23g)'/></svg>",
    description: "Organic green freshness for eco-friendly goods, botanicals, and fitness gear",
    lighting: {
      shadowIntensity: 0.3,
      shadowBlur: 14,
      shadowOffsetX: 0,
      shadowOffsetY: 10,
      groundReflection: false,
    },
  },
  {
    id: "bg-grad-cyber-dark",
    name: "Cyber Neon Indigo",
    category: "gradient",
    type: "gradient",
    value: "linear-gradient(135deg, #090D16 0%, #1E1B4B 50%, #311042 100%)",
    previewThumbnail: "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='80' height='80'><defs><linearGradient id='g' x1='0' y1='0' x2='1' y2='1'><stop offset='0%25' stop-color='%23090D16'/><stop offset='50%25' stop-color='%231E1B4B'/><stop offset='100%25' stop-color='%23311042'/></linearGradient></defs><rect width='80' height='80' fill='url(%23g)'/></svg>",
    description: "Gaming and futuristic deep indigo illumination",
    badge: "Gaming / Tech",
    lighting: {
      shadowIntensity: 0.7,
      shadowBlur: 28,
      shadowOffsetX: 0,
      shadowOffsetY: 20,
      groundReflection: true,
      ambientLightColor: "#818CF8",
      ambientLightIntensity: 0.4,
    },
  },

  // 3. STUDIO BACKGROUNDS (Spotlight, Cyclorama, Dual-Point Light)
  {
    id: "bg-studio-spotlight",
    name: "Spotlight Center Stage",
    category: "studio",
    type: "gradient",
    value: "radial-gradient(circle at 50% 45%, #FFFFFF 0%, #E5E7EB 55%, #D1D5DB 100%)",
    previewThumbnail: "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='80' height='80'><defs><radialGradient id='r' cx='50%25' cy='45%25' r='50%25'><stop offset='0%25' stop-color='%23FFFFFF'/><stop offset='55%25' stop-color='%23E5E7EB'/><stop offset='100%25' stop-color='%23D1D5DB'/></radialGradient></defs><rect width='80' height='80' fill='url(%23r)'/></svg>",
    description: "Professional top-down spotlight with smooth atmospheric falloff",
    badge: "Commercial Studio",
    lighting: {
      shadowIntensity: 0.45,
      shadowBlur: 20,
      shadowOffsetX: 0,
      shadowOffsetY: 16,
      groundReflection: true,
    },
  },
  {
    id: "bg-studio-cyclorama",
    name: "Infinite Cyclorama Wall",
    category: "studio",
    type: "gradient",
    value: "linear-gradient(180deg, #F8FAFC 0%, #EEF2F6 65%, #E2E8F0 66%, #CBD5E1 100%)",
    previewThumbnail: "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='80' height='80'><defs><linearGradient id='g' x1='0' y1='0' x2='0' y2='1'><stop offset='0%25' stop-color='%23F8FAFC'/><stop offset='65%25' stop-color='%23EEF2F6'/><stop offset='66%25' stop-color='%23E2E8F0'/><stop offset='100%25' stop-color='%23CBD5E1'/></linearGradient></defs><rect width='80' height='80' fill='url(%23g)'/></svg>",
    description: "Seamless curved studio horizon line with realistic ground floor transition",
    lighting: {
      shadowIntensity: 0.5,
      shadowBlur: 18,
      shadowOffsetX: 0,
      shadowOffsetY: 14,
      groundReflection: true,
    },
  },
  {
    id: "bg-studio-warm-ambient",
    name: "Golden Hour Studio",
    category: "studio",
    type: "gradient",
    value: "radial-gradient(circle at 75% 30%, #FEF3C7 0%, #F3F4F6 50%, #E5E7EB 100%)",
    previewThumbnail: "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='80' height='80'><defs><radialGradient id='r' cx='75%25' cy='30%25' r='60%25'><stop offset='0%25' stop-color='%23FEF3C7'/><stop offset='50%25' stop-color='%23F3F4F6'/><stop offset='100%25' stop-color='%23E5E7EB'/></radialGradient></defs><rect width='80' height='80' fill='url(%23r)'/></svg>",
    description: "Warm side key light creating dimensional shadows and organic depth",
    lighting: {
      shadowIntensity: 0.4,
      shadowBlur: 16,
      shadowOffsetX: -8,
      shadowOffsetY: 14,
      groundReflection: false,
    },
  },

  // 4. E-COMMERCE PRODUCT BACKGROUNDS (Pedestal, Marble, Wood, Geometric)
  {
    id: "bg-ecom-marble",
    name: "White Carrara Marble",
    category: "ecommerce",
    type: "image",
    value: "https://images.unsplash.com/photo-1590381105924-c72589b9ef3f?auto=format&fit=crop&w=1200&q=80",
    previewThumbnail: "https://images.unsplash.com/photo-1590381105924-c72589b9ef3f?auto=format&fit=crop&w=160&q=80",
    description: "Premium Italian white marble slab for jewelry, cosmetics, and fine accessories",
    badge: "Top Rated",
    lighting: {
      shadowIntensity: 0.45,
      shadowBlur: 14,
      shadowOffsetX: 0,
      shadowOffsetY: 12,
      groundReflection: true,
    },
  },
  {
    id: "bg-ecom-pedestal",
    name: "Minimalist Concrete Podium",
    category: "ecommerce",
    type: "image",
    value: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1200&q=80",
    previewThumbnail: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=160&q=80",
    description: "Clean cylindrical geometric platform with subtle soft ambient light",
    badge: "Showcase",
    lighting: {
      shadowIntensity: 0.4,
      shadowBlur: 16,
      shadowOffsetX: 0,
      shadowOffsetY: 14,
      groundReflection: false,
    },
  },
  {
    id: "bg-ecom-wood",
    name: "Natural Light Oak Table",
    category: "ecommerce",
    type: "image",
    value: "https://images.unsplash.com/photo-1533090161767-e6ffed986c88?auto=format&fit=crop&w=1200&q=80",
    previewThumbnail: "https://images.unsplash.com/photo-1533090161767-e6ffed986c88?auto=format&fit=crop&w=160&q=80",
    description: "Warm organic Scandinavian wooden surface for artisanal, kitchen & leather items",
    lighting: {
      shadowIntensity: 0.42,
      shadowBlur: 14,
      shadowOffsetX: 2,
      shadowOffsetY: 12,
      groundReflection: false,
    },
  },
  {
    id: "bg-ecom-pastel-geometry",
    name: "Pastel Boutique Blocks",
    category: "ecommerce",
    type: "image",
    value: "https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=1200&q=80",
    previewThumbnail: "https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=160&q=80",
    description: "Modern editorial pastel staging blocks with soft diffuse illumination",
    lighting: {
      shadowIntensity: 0.35,
      shadowBlur: 18,
      shadowOffsetX: 0,
      shadowOffsetY: 14,
      groundReflection: false,
    },
  },

  // 5. MINIMAL (Warm Almond, Ice Blue, Sage Whisper, Soft Sand)
  {
    id: "bg-min-warm-almond",
    name: "Warm Almond Cream",
    category: "minimal",
    type: "color",
    value: "#FBF8F5",
    previewThumbnail: "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='80' height='80'><rect width='80' height='80' fill='%23FBF8F5'/></svg>",
    description: "Cozy warm neutral that prevents harsh glare and adds comforting feel",
    lighting: {
      shadowIntensity: 0.35,
      shadowBlur: 15,
      shadowOffsetX: 0,
      shadowOffsetY: 12,
    },
  },
  {
    id: "bg-min-ice-blue",
    name: "Ice Blue Tint",
    category: "minimal",
    type: "color",
    value: "#F0F7FF",
    previewThumbnail: "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='80' height='80'><rect width='80' height='80' fill='%23F0F7FF'/></svg>",
    description: "Subtle cool atmosphere that enhances crystal, electronics and winter items",
    lighting: {
      shadowIntensity: 0.38,
      shadowBlur: 16,
      shadowOffsetX: 0,
      shadowOffsetY: 14,
    },
  },
  {
    id: "bg-min-sage-whisper",
    name: "Sage Leaf Whisper",
    category: "minimal",
    type: "color",
    value: "#F2F7F4",
    previewThumbnail: "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='80' height='80'><rect width='80' height='80' fill='%23F2F7F4'/></svg>",
    description: "Clean wellness green tint that conveys health and sustainability",
    lighting: {
      shadowIntensity: 0.32,
      shadowBlur: 14,
      shadowOffsetX: 0,
      shadowOffsetY: 10,
    },
  },
  {
    id: "bg-min-soft-sand",
    name: "Soft Dune Sand",
    category: "minimal",
    type: "color",
    value: "#F7F5F0",
    previewThumbnail: "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='80' height='80'><rect width='80' height='80' fill='%23F7F5F0'/></svg>",
    description: "Earthy beige tone for footwear, outdoor gear and rustic collections",
    lighting: {
      shadowIntensity: 0.35,
      shadowBlur: 16,
      shadowOffsetX: 0,
      shadowOffsetY: 12,
    },
  },

  // 6. LIFESTYLE (Modern Workspace, Kitchen Counter, Sunlit Interior, Botanical)
  {
    id: "bg-life-workspace",
    name: "Modern Minimalist Desk",
    category: "lifestyle",
    type: "image",
    value: "https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=1200&q=80",
    previewThumbnail: "https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=160&q=80",
    description: "Bright airy Scandinavian office desk for gadgets, stationery and tech",
    badge: "Lifestyle",
    lighting: {
      shadowIntensity: 0.4,
      shadowBlur: 18,
      shadowOffsetX: 0,
      shadowOffsetY: 14,
    },
  },
  {
    id: "bg-life-sunlit-living",
    name: "Sunlit Morning Interior",
    category: "lifestyle",
    type: "image",
    value: "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1200&q=80",
    previewThumbnail: "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=160&q=80",
    description: "Warm morning rays through sheer curtains on a cozy credenza",
    lighting: {
      shadowIntensity: 0.35,
      shadowBlur: 20,
      shadowOffsetX: 6,
      shadowOffsetY: 16,
    },
  },
  {
    id: "bg-life-botanical-sunlight",
    name: "Botanical Sunlit Patio",
    category: "lifestyle",
    type: "image",
    value: "https://images.unsplash.com/photo-1501004318641-b39e6451bec6?auto=format&fit=crop&w=1200&q=80",
    previewThumbnail: "https://images.unsplash.com/photo-1501004318641-b39e6451bec6?auto=format&fit=crop&w=160&q=80",
    description: "Soft focus lush foliage with dappled natural sunlight",
    lighting: {
      shadowIntensity: 0.3,
      shadowBlur: 16,
      shadowOffsetX: 4,
      shadowOffsetY: 12,
    },
  },
  {
    id: "bg-life-kitchen",
    name: "Modern Kitchen Countertop",
    category: "lifestyle",
    type: "image",
    value: "https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=1200&q=80",
    previewThumbnail: "https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=160&q=80",
    description: "Bright clean kitchen granite backdrop for gourmet cookware and appliances",
    lighting: {
      shadowIntensity: 0.42,
      shadowBlur: 16,
      shadowOffsetX: 0,
      shadowOffsetY: 14,
    },
  },
];
